import Head from 'next/head';
import '../styles/globals.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Payments</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className="flex w-4 h-6 bg-black"></main>
      </div>
    </>
  );
}
